config/routes.rb
Brackets::Application.routes.draw do
  resources :picks

  devise_for :users

  resources :tournaments

  resources :pools do
    resources :brackets
  end

  root :to => "tournaments#index"

end

app/models/pool.rb
class Pool
  include Mongoid::Document
  field :name, :type => String
  field :owner, :type => String
  field :tournament_id
  embeds_many :brackets

  def tournament
    @tournament ||= Tournament.find(tournament_id)
  end

  def owner_name
     if(owner.nil?)
	     "coward"
     else
	     User.find(owner).email
     end
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /pools
  # GET /pools.xml
  def index
    @pools = Pool.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @pools }
    end
  end

  # GET /pools/1
  # GET /pools/1.xml
  def show
    @pool = Pool.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @pool }
    end
  end

  # GET /pools/new
  # GET /pools/new.xml
  def new
    @pool = Pool.new
    @tournaments = Tournament.all.collect{|t| [t.name, t._id] }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @pool }
    end
  end

  # GET /pools/1/edit
  def edit
    @pool = Pool.find(params[:id])
    @tournaments = Tournament.all.collect{|t| [t.name, t._id] }
  end

  # POST /pools
  # POST /pools.xml
  def create
    @pool = Pool.new(params[:pool])
    @pool.owner = current_user._id

    respond_to do |format|
      if @pool.save
        format.html { redirect_to(@pool, :notice => 'Pool was successfully created.') }
        format.xml  { render :xml => @pool, :status => :created, :location => @pool }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /pools/1
  # PUT /pools/1.xml
  def update
    @pool = Pool.find(params[:id])

    respond_to do |format|
      if @pool.update_attributes(params[:pool])
        format.html { redirect_to(@pool, :notice => 'Pool was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @pool.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.xml
  def destroy
    @pool = Pool.find(params[:id])
    @pool.destroy

    respond_to do |format|
      format.html { redirect_to(pools_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_for(@pool) do |f| %>
  <% if @pool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pool.errors.count, "error") %> prohibited this pool from being saved:</h2>

      <ul>
      <% @pool.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>Name: <%= f.text_field :name %></div>
  <div>Tournament: <%= f.select(:tournament_id, options_for_select( @tournaments, -1)) %></div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pools/edit.html.erb
<h1>Editing pool</h1>

<%= render 'form' %>

<%= link_to 'Show', @pool %> |
<%= link_to 'Back', pools_path %>

app/views/pools/index.html.erb
<h1>Listing pools</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pools.each do |pool| %>
  <tr>
    <td><%= pool.name %></td>
    <td><%= link_to 'Show', pool %></td>
    <td><%= link_to 'Edit', edit_pool_path(pool) %></td>
    <td><%= link_to 'Destroy', pool, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pool', new_pool_path %>

app/views/pools/new.html.erb
<h1>New pool</h1>

<%= render 'form' %>

<%= link_to 'Back', pools_path %>

app/views/pools/show.html.erb
<p id="notice"><%= notice %></p>

<div>Name: <%= @pool.name %></div>
<div>Owner: <%= @pool.owner_name %></div>

<div>
  <div><%= link_to 'Join this pool', new_pool_bracket_path(@pool) %></div>
</div>

<table>
  <% @pool.brackets.each do |b| %>
  <tr>
    <td><%= b.owner %></td>
    <td><%= b.name %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_pool_path(@pool) %> |
<%= link_to 'Back', pools_path %>