config/routes.rb
Brackets::Application.routes.draw do
  resources :picks

  devise_for :users

  resources :tournaments

  resources :pools do
    resources :brackets
  end

  root :to => "tournaments#index"

end

app/models/tournament.rb
class Tournament
  include Mongoid::Document
  field :name
  field :start_time, :type => Date
  embeds_many :seedings, :class_name => "Seeding"
  embeds_one :opening_round, :class_name => "Game"

  accepts_nested_attributes_for :seedings
  def regions
    ["Midwest", "West", "East", "South"]
  end

  def seeding_for_team(name)
    seedings.select{|s| s.team == name}.first
  end

  def populate_seeds
    regions.each do |region|
      (1..17).collect do |seed|
        seeding = Seeding.new
	seeding.region = region
	seeding.seed = seed
        self.seedings << seeding
      end
    end
  end
  def regions_and_teams_sorted
    teams_by_region = seedings.inject([]) do |array, seeding|
      index = regions.index(seeding.region)
      array[index] ||= []
      array[index] << seeding
      array
    end
    teams_by_region.each do |seedings|
      seedings.sort!{|a, b| a.seed <=> b.seed}
    end
    teams_by_region
  end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  # GET /tournaments
  # GET /tournaments.xml
  def index
    @tournaments = Tournament.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tournaments }
    end
  end

  # GET /tournaments/1
  # GET /tournaments/1.xml
  def show
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tournament }
    end
  end

  # GET /tournaments/new
  # GET /tournaments/new.xml
  def new
    @tournament = Tournament.new
    @tournament.populate_seeds

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tournament }
    end
  end

  # GET /tournaments/1/edit
  def edit
    @tournament = Tournament.find(params[:id])
  end

  # POST /tournaments
  # POST /tournaments.xml
  def create
    seedings = params[:tournament].delete(:seedings_attributes)
    @tournament = Tournament.new(params[:tournament])
    
    seedings.each_value do |seed_attributes|
      seed = Seeding.new
      seed.team = seed_attributes[:team]
      seed.region = seed_attributes[:region]
      seed.seed = seed_attributes[:seed]

      @tournament.seedings << seed
    end

    respond_to do |format|
      if @tournament.save
        format.html { redirect_to(@tournament, :notice => 'Tournament was successfully created.') }
        format.xml  { render :xml => @tournament, :status => :created, :location => @tournament }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tournament.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tournaments/1
  # PUT /tournaments/1.xml
  def update
    @tournament = Tournament.find(params[:id])

    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to(@tournament, :notice => 'Tournament was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tournament.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tournaments/1
  # DELETE /tournaments/1.xml
  def destroy
    @tournament = Tournament.find(params[:id])
    @tournament.destroy

    respond_to do |format|
      format.html { redirect_to(tournaments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <% if @tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
      <% @tournament.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div>Name: <%= f.text_field :name %></div>
  <div>Start Time: <%= f.text_field :start_time %></div>

  <table>
	  <tr>
		  <th>Seed</th>
		  <th>Team</th>
		  <th>Region</th>
	  </tr>
  <%= f.fields_for :seedings do |builder| %>
	  <tr>
		  <td><%= builder.object.seed %></td>
		  <td><%= builder.text_field :team %></td>
		  <td><%= builder.object.region %></td>
		  <td></td>
		  <%= builder.hidden_field :region %>
		  <%= builder.hidden_field :seed %>
	  </tr>
  <% end %>
  </table>


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tournaments/edit.html.erb
<h1>Editing tournament</h1>

<%= render 'form' %>

<%= link_to 'Show', @tournament %> |
<%= link_to 'Back', tournaments_path %>

app/views/tournaments/index.html.erb
<h1>Listing tournaments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start Time</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tournaments.each do |tournament| %>
  <tr>
    <td><%= tournament.name %></td>
    <td><%= tournament.start_time %></td>
    <td><%= link_to 'Show', tournament %></td>
    <td><%= link_to 'Edit', edit_tournament_path(tournament) %></td>
    <td><%= link_to 'Destroy', tournament, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tournament', new_tournament_path %>

app/views/tournaments/new.html.erb
<h1>New tournament</h1>

<%= render 'form' %>

<%= link_to 'Back', tournaments_path %>

app/views/tournaments/show.html.erb
<p id="notice"><%= notice %></p>

<div>Name: <%= @tournament.name %></div>
<div>Start Time: <%= @tournament.start_time %></div>

<% @tournament.seedings.each do |seeding| %>
  <div><%= "#{seeding.team}, #{seeding.seed}, #{seeding.region}" %></div>
<% end %>

<%= link_to 'Edit', edit_tournament_path(@tournament) %> |
<%= link_to 'Back', tournaments_path %>